services:
  db:
    container_name: postgres_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    
    volumes:
      - pgdata:/var/lib/postgresql/data 
 
volumes:
  pgdata:
